name: Rotki
description: Rotki is an open source portfolio tracking, analytics, accounting, and tax reporting tool that protects your privacy.
instructions: null
changeLog:
  - date: 2023-2-9
    description: first release
links:
  - label: Documentation
    url: https://github.com/rotki/rotki
  - label: Github
    url: https://github.com/boypt/simple-torrent
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rotki
    appServiceImage:
      type: string
      title: App Service Image
      default: rotki/rotki:v1.27.0
