name: Radicale
description: A simple CalDAV (calendar) and CardDAV (contact) server
instructions: Login with any username or password
changeLog:
  - date: 2023-3-27
    description: first release
links:
  - label: Website
    url: https://radicale.org/
  - label: Documentation
    url: https://radicale.org/v3.html
  - label: Github
    url: https://github.com/Kozea/Radicale
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: radicale
    appServiceImage:
      type: string
      title: App Service Image
      default: tomsquest/docker-radicale:3.1.8.1
