name: Fider
description: The premiere source of truth powering network automation.
instructions: null
changeLog:
  - date: 2023-3-17
    description: first release
links:
  - label: Website
    url: https://netbox.dev
  - label: Documentation
    url: https://docs.netbox.dev/
  - label: Github
    url: https://github.com/netbox-community/netbox
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - domain
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: fider
    domain:
      type: string
      title: Domain
    appServiceImage:
      type: string
      title: App Service Image
      default: getfider/fider:stable
    databaseServiceName:
      type: string
      title: Database Service Name
      default: fider-db
    emailNoReply:
      type: string
      title: No Reply Email
    emailHost:
      type: string
      title: Email Host
    emailPort:
      type: number
      title: Email Port
      default: 587
    emailUsername:
      type: string
      title: Email Username
    emailPassword:
      type: string
      title: Email Password
