name: Pufferpanel
description: https://github.com/PufferPanel/PufferPanel
instructions: Run ./pufferpanel user create
changeLog:
  - date: 2023-3-21
    description: first release
links:
  - label: Website
    url: https://pufferpanel.com/
  - label: Documentation
    url: https://docs.pufferpanel.com/en/latest
  - label: Github
    url: https://github.com/PufferPanel/PufferPanel
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: pufferpanel
    appServiceImage:
      type: string
      title: App Service Image
      default: pufferpanel/pufferpanel:2.6.6
