name: YAO
description: YAO is an open-source application engine,
instructions: Use xiang@iqka.com:A123456p+ to login at /xiang/login/admin . Use amd64 instead of arm64 if you use a non ARM based system.
changeLog:
  - date: 2023-3-14
    description: first release
links:
  - label: Website
    url: https://yaoapps.com/
  - label: Documentation
    url: https://yaoapps.com/en-US/doc/
  - label: Github
    url: https://github.com/YaoApp/yao
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wordpress
    appServiceImage:
      type: string
      title: App Service Image
      default: yaoapp/yao:0.10.3-arm64
    databaseServiceName:
      type: string
      title: Database Service Name
      default: yao-db
