name: StandardNotes
description:
  StandardNotes is a private, end-to-end encrypted notes app that provides a
  secure platform for writing and organizing your thoughts. It offers a clean,
  distraction-free interface with strong encryption to protect your privacy. The
  self-hosted version gives you complete control over your data while
  maintaining all the security features of the cloud version.
instructions: null
changeLog:
  - date: 2025-09-16
    description: Template Release (9b023782830a4742b31cd3696cc2f8fff22e0936)
links:
  - label: Documentation
    url: https://docs.standardnotes.com/self-hosting/getting-started
  - label: Github
    url: https://github.com/standardnotes/app
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh

schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: standardnotes
    appServiceImage:
      type: string
      title: Web Service Image
      default: standardnotes/web:9b023782830a4742b31cd3696cc2f8fff22e0936

benefits:
  - title: End-to-End Encryption
    description:
      Your notes are encrypted on your device before being sent to the server,
      ensuring complete privacy and security of your personal data.
  - title: Self-Hosted Privacy
    description:
      Complete control over your data with self-hosted deployment, ensuring your
      notes never leave your own infrastructure.
  - title: Clean, Distraction-Free Interface
    description:
      Minimalist design focused on writing without distractions, helping you
      concentrate on your thoughts and ideas.

features:
  - title: Secure Note Taking
    description:
      Write and organize notes with strong encryption protecting your content
      from unauthorized access or data breaches.
  - title: Multi-Platform Access
    description:
      Access your notes from any device with web browsers, mobile apps, and
      desktop applications for seamless note-taking across platforms.
  - title: File Attachments
    description:
      Attach files to your notes with the same encryption protection, keeping
      all your documents secure and organized.
  - title: Tagging and Organization
    description:
      Organize your notes with tags, folders, and search functionality to
      quickly find and manage your content.
  - title: Version History
    description:
      Track changes to your notes over time with automatic version history and
      the ability to restore previous versions.
  - title: Offline Access
    description:
      Work on your notes even when offline, with automatic synchronization when
      you reconnect to the internet.

tags:
  - Notes App
  - Encryption
  - Self-Hosted
  - Privacy
  - Writing
  - Productivity
