name: Tooljet
description:
  Tooljet is an open-source low-code platform for building internal tools and
  business applications. It provides a visual interface builder, database
  connectors, API integrations, and workflow automation capabilities. With
  Tooljet, teams can quickly build custom dashboards, admin panels, CRUD
  applications, and complex business tools without extensive coding. The
  platform supports multiple data sources, real-time collaboration, and
  enterprise-grade security features.
instructions:
  Please run migrations inside the tooljet container if required, it will take
  2-3 minutes to complete. "npm run db:migrate:prod"
changeLog:
  - date: 2025-09-09
    description: Initial Template Release (v3.15.1)
links:
  - label: GitHub
    url: https://github.com/ToolJet/ToolJet
  - label: Documentation
    url: https://docs.tooljet.com/
  - label: Docker Hub
    url: https://hub.docker.com/r/tooljet/tooljet
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: tooljet
    appServiceImage:
      type: string
      title: App Service Image
      default: tooljet/tooljet-ce:v3.15.1
      description: Tooljet Docker image
    temporalImage:
      type: string
      title: Temporal Image
      default: temporalio/auto-setup:1.25.1
      description: Temporal server Docker image
benefits:
  - title: Low-Code Development
    description:
      Build complex business applications and internal tools using a visual
      interface builder without extensive coding knowledge or development
      resources.
  - title: Rapid Prototyping
    description:
      Quickly prototype and iterate on business ideas with drag-and-drop
      components, pre-built integrations, and real-time collaboration features.
  - title: Data Source Integration
    description:
      Connect to multiple data sources including databases, APIs, cloud
      services, and third-party tools through pre-built connectors and custom
      integrations.
  - title: Enterprise Security
    description:
      Built-in security features including authentication, authorization, audit
      logs, and compliance tools for enterprise-grade applications.
features:
  - title: Visual Interface Builder
    description:
      Drag-and-drop interface builder with pre-built components for forms,
      tables, charts, and custom widgets for creating rich user interfaces.
  - title: Database Connectors
    description:
      Support for multiple database types including PostgreSQL, MySQL, MongoDB,
      and cloud databases with real-time data synchronization.
  - title: API Integration
    description:
      Built-in API client with support for REST, GraphQL, and webhook
      integrations for connecting to external services and data sources.
  - title: Workflow Automation
    description:
      Visual workflow builder powered by Temporal for creating complex business
      processes and automated workflows.
  - title: Real-Time Collaboration
    description:
      Multi-user collaboration features with real-time updates, comments, and
      version control for team-based development.
  - title: Custom Components
    description:
      Extend functionality with custom components, plugins, and integrations
      using JavaScript and React for advanced use cases.
tags:
  - Low-Code
  - Internal Tools
  - Business Applications
  - Dashboard
  - Database
  - API
  - Workflow
  - Automation
  - Visual Builder
  - Enterprise
